render-e2e-tests-examples: TEST_SUITE_NAME=examples
render-e2e-tests-examples: generate-kuttl-config
	./tests/e2e/examples/render.sh

run-e2e-tests-examples: TEST_SUITE_NAME=examples
run-e2e-tests-examples: run-suite-tests
