version: 2
updates:
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
      time: "03:00"
      timezone: "Europe/Berlin"
  - package-ecosystem: docker
    directory: "/tests"
    schedule:
      interval: daily
      time: "03:00"
      timezone: "Europe/Berlin"
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
      time: "03:00"
      timezone: "Europe/Berlin"
    groups:
      golang-org-x:
        patterns:
          - "golang.org/x/*"
      opentelemetry:
        patterns:
          - "go.opentelemetry.io/*"
      prometheus:
        patterns:
          - "github.com/prometheus-operator/prometheus-operator"
          - "github.com/prometheus-operator/prometheus-operator/*"
          - "github.com/prometheus/prometheus"
          - "github.com/prometheus/prometheus/*"
          - "github.com/prometheus/client_go"
          - "github.com/prometheus/client_go/*"
      kubernetes:
        patterns:
          - "k8s.io/*"
          - "sigs.k8s.io/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "Europe/Berlin"
