apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
- patch: |-
    $patch: delete
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: jaeger-operator-metrics-reader
- patch: |
    - op: replace
      path: /kind
      value: Role
  target:
    group: rbac.authorization.k8s.io
    kind: ClusterRole
- patch: |
    - op: replace
      path: /roleRef/kind
      value: Role
  target:
    group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
- patch: |
    - op: replace
      path: /kind
      value: RoleBinding
  target:
    group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding

- target:
    group: apps
    version: v1
    name: jaeger-operator
    kind: Deployment
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/valueFrom/fieldRef/fieldPath
      value: metadata.namespace
