ignore:
  - "apis/jaegertracing/v1/zz_generated.deepcopy.go"
  - "apis/jaegertracing/v1/zz_generated.defaults.go"
  - "apis/jaegertracing/v1/zz_generated.openapi.go"
  - "apis/kafka/v1beta2/zz_generated.deepcopy.go"
  - "apis/kafka/v1beta2/zz_generated.openapi.go"
