coverage:
  status:
    project:
      default:
        target: auto
        # this allows a 0.1% drop from the previous base commit coverage
        threshold: 0.1%
ignore:
  - "apis/v1/zz_generated.deepcopy.go"
  - "apis/v1/zz_generated.defaults.go"
  - "apis/v1/zz_generated.openapi.go"
  - "apis/v1/groupversion_info.go"
  - "pkg/kafka/v1beta2/zz_generated.deepcopy.go"
  - "pkg/kafka/v1beta2/zz_generated.openapi.go"
  - "pkg/kafka/v1beta2/groupversion_info.go"
  - "pkg/util/k8s_utils.go"
