ignore:
  - "pkg/apis/io/v1alpha1/zz_generated.deepcopy.go"
  - "pkg/apis/jaegertracing/v1/zz_generated.deepcopy.go"
  - "pkg/apis/io/v1alpha1/zz_generated.defaults.go"
  - "pkg/apis/jaegertracing/v1/zz_generated.defaults.go"
  - "pkg/apis/kafka/v1beta1/zz_generated.deepcopy.go"
  - "pkg/apis/kafka/v1beta1/zz_generated.openapi.go"
