issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gosec
    - linters:
        - staticcheck
      text: "SA1019:"

linters-settings:
  goimports:
    local-prefixes: github.com/jaegertracing/jaeger-operator
  gosimple:
    go: "1.22"

linters:
  enable:
    - bidichk
    - errorlint
    - gofumpt
    - goimports
    - gosec
    - govet
    - misspell
    - testifylint
  disable:
    - errcheck

run:
  go: '1.22'
  timeout: 10m
