apiVersion: kuttl.dev/v1beta1
kind: TestSuite
startKIND: true
crdDir: ./tests/_build/crds/
artifactsDir: ./tests/_build/artifacts/
kindContainers:
  - local/jaeger-operator:e2e
commands:
  - command: kubectl create namespace jaeger-operator-system
  - command: kubectl apply -f ./tests/_build/manifests/01-jaeger-operator.yaml -n jaeger-operator-system
  - command: kubectl wait --timeout=5m --for=condition=available deployment jaeger-operator -n jaeger-operator-system
  - command: sleep 5s

testDirs:
  - ./tests/e2e/
