apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-operator
  labels:
spec:
  selector:
    matchLabels:
  strategy: {}
  replicas: 1
  template:
    metadata:
      labels:
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - command:
        - /jaeger-operator
        args:
        - start
        - --leader-elect
        image: controller:latest
        name: jaeger-operator
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['olm.targetNamespaces']
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OPERATOR_NAME
          value: "jaeger-operator"
      serviceAccountName: jaeger-operator
      terminationGracePeriodSeconds: 10
