render-e2e-tests-smoke: TEST_SUITE_NAME=smoke
render-e2e-tests-smoke: generate-kuttl-config
	./tests/e2e/smoke/render.sh

run-e2e-tests-smoke: TEST_SUITE_NAME=smoke
run-e2e-tests-smoke: run-suite-tests
