apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: jaeger-operator
  name: jaeger-operator-webhook-service
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    name: jaeger-operator
status:
  loadBalancer: {}
