resources:
  - manifests.yaml
  - service.yaml

configurations:
  - kustomizeconfig.yaml

patchesStrategicMerge:
  - namespace_inject_patch.yaml
  - pod_inject_patch.yaml
  - component_inject_patch.yaml