apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
  - name: namespace.sidecar-injector.jaegertracing.io
    namespaceSelector: # we only need to watch for pods in the namespace that is labelled with "sidecar.jaegertracing.io/inject"
      matchExpressions:
        - key: jaeger-injection
          operator: In
          values:
            - "enabled"
    objectSelector: # also skip pods that have been already injected (prevent from being injected twice by multiple operators)
      matchExpressions:
        - key: sidecar.jaegertracing.io/inject
          operator: NotIn
          values:
            - "false"
        - key: sidecar.jaegertracing.io/injected # set by deployment controller
          operator: DoesNotExist