apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
  - name: object.sidecar-injector.jaegertracing.io
    namespaceSelector:
      matchExpressions:
        - key: jaeger-injection
          operator: DoesNotExist
    objectSelector: # also skip pods that have been already injected (prevent from being injected twice by multiple operators)
      matchExpressions:
        - key: sidecar.jaegertracing.io/inject
          operator: In
          values:
            - "true"
        - key: sidecar.jaegertracing.io/injected # set by deployment controller
          operator: DoesNotExist