version: 2.1
jobs:
  build:
    machine:
      image: circleci/classic:201808-01
    steps:
      - checkout
      - run:
          command: >-
            curl -L https://golang.org/dl/go1.14.3.linux-amd64.tar.gz | sudo tar -xz -C /usr/local/ &&
            sudo chown -R $(whoami): /usr/local/go &&
            echo "export PATH=$PATH:/usr/local/go/bin" >> $BASH_ENV &&
            go version
          name: Install recent go

      - run:
          command: >-
            curl -Lo minikube https://github.com/kubernetes/minikube/releases/download/v1.12.1/minikube-linux-amd64 &&
              chmod +x minikube &&
              sudo mv minikube /usr/local/bin/
          name: Install minikube

      - run:
          command: >-
            curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.18.3/bin/linux/amd64/kubectl &&
              chmod +x kubectl &&
              sudo mv kubectl /usr/local/bin/ &&
              mkdir -p ${HOME}/.kube && touch ${HOME}/.kube/config
          name: Install kubectl

      - run:
          command: >-
            sudo -E minikube start --vm-driver=none --kubernetes-version=v1.17.9
          name: Start minikube

      - run: make install-sdk SDK_VERSION=0.18.2 
      - run: make install-tools
      - run: ./.ci/run-e2e-tests.sh TEST_GROUP=smoke 
