render-e2e-tests-sidecard: TEST_SUITE_NAME=sidecard
render-e2e-tests-sidecard: generate-kuttl-config
	./tests/e2e/sidecard/render.sh

run-e2e-tests-sidecard: TEST_SUITE_NAME=sidecard
run-e2e-tests-sidecard: run-suite-tests
