apiVersion: "io.jaegertracing/v1alpha1"
kind: "Jaeger"
metadata:
  name: "my-jaeger"
spec:
  strategy: allInOne
  allInOne:
    image: jaegertracing/all-in-one:1.7
    options:
      log-level: debug
      memory.max-traces: 100000
