apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane:  jaeger-operator
  name: jaeger-operator-metrics
  namespace: system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    name: jaeger-operator
