render-e2e-tests-outside-cluster: TEST_SUITE_NAME=outside-cluster
render-e2e-tests-outside-cluster: generate-kuttl-config

run-e2e-tests-outside-cluster: TEST_SUITE_NAME=outside-cluster
run-e2e-tests-outside-cluster: run-suite-tests
