apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-prod-elasticsearch
spec:
  strategy: production
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://elasticsearch.default.svc:9200
