render-e2e-tests-allinone: TEST_SUITE_NAME=allinone
render-e2e-tests-allinone: generate-kuttl-config
	./tests/e2e/allinone/render.sh

run-e2e-tests-allinone: TEST_SUITE_NAME=allinone
run-e2e-tests-allinone: run-suite-tests
