apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-priority # priorityClassName here
value: 1000000
globalDefault: false
description: "This priority class should be used for XYZ service pods only."
---
apiVersion: jaegertracing.io/v1
kind: "Jaeger"
metadata:
  name: "my-jaeger"
spec:
  strategy: allInOne
  allInOne:
    image: jaegertracing/all-in-one:1.30.0
    priorityClassName: high-priority # priorityClassName here