apiVersion: scheduling.k8s.io/v1 
kind: PriorityClass
metadata:
  name: collector-high-priority
value: 1000000
globalDefault: false
description: "This priority class should be used for XYZ service pods only."
---
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: collector-with-high-priority
spec:
  collector:
    priorityClassName: collector-high-priority