apiVersion: v1
kind: ServiceAccount
metadata:
  name: customsa
---
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: custom-serviceaccount
spec:
  serviceAccount: customsa # this is created and managed externally to the operator
