apiVersion: scheduling.k8s.io/v1 
kind: PriorityClass
metadata:
  name: query-high-priority
value: 1000000
globalDefault: false
description: "This priority class should be used for XYZ service pods only."
---
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: query-with-high-priority
spec:
  query:
    priorityClassName: query-high-priority