# setup an elasticsearch with `make es`
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-prod
spec:
  strategy: production
  storage:
    type: elasticsearch
    options:
      es:
        # Note: This assumes elasticsearch is running in the "default" namespace.
        server-urls: http://elasticsearch.default.svc:9200
  volumeMounts:
  - name: elastic-data
    mountPath: /usr/share/elasticsearch/data
  volumes:
  - name: elastic-data
    emptyDir: {}
