render-e2e-tests-cassandra: TEST_SUITE_NAME=cassandra
render-e2e-tests-cassandra: generate-kuttl-config
	./tests/e2e/cassandra/render.sh

run-e2e-tests-cassandra: TEST_SUITE_NAME=cassandra
run-e2e-tests-cassandra: run-suite-tests
