render-e2e-tests-elasticsearch: TEST_SUITE_NAME=elasticsearch
render-e2e-tests-elasticsearch: generate-kuttl-config
	./tests/e2e/elasticsearch/render.sh

run-e2e-tests-elasticsearch: TEST_SUITE_NAME=elasticsearch
run-e2e-tests-elasticsearch: run-suite-tests
