render-e2e-tests-istio: TEST_SUITE_NAME=istio
render-e2e-tests-istio: generate-kuttl-config
	./tests/e2e/istio/render.sh

run-e2e-tests-istio: TEST_SUITE_NAME=istio
run-e2e-tests-istio: run-suite-tests
