render-e2e-tests-miscellaneous: load-assert-job
	SKIP_ES_EXTERNAL=$(SKIP_ES_EXTERNAL) ./tests/e2e/miscellaneous/render.sh

run-e2e-tests-miscellaneous: TEST_SUITE_NAME=miscellaneous
run-e2e-tests-miscellaneous: run-suite-tests
