render-e2e-tests-streaming: TEST_SUITE_NAME=streaming
render-e2e-tests-streaming: generate-kuttl-config
	./tests/e2e/streaming/render.sh

run-e2e-tests-streaming: TEST_SUITE_NAME=streaming
run-e2e-tests-streaming: run-suite-tests
