name: Outside cluster E2E tests

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'

concurrency:
  group: e2e-tests-${{ github.ref }}-outside-cluster
  cancel-in-progress: true

jobs:
  run-e2e-outside-cluster-test-suite:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
       kube-version:
       - "1.19"
       - "1.23"
    name: Run outside cluster E2E tests
    steps:
      - name: "Check out code into the Go module directory"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./hack/actions/e2e
        with:
          testsuite_name: outside-cluster
          kube_version: ${{ matrix.kube-version }}
