name: Sidecar E2E tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-e2e-sidecar-test-suite:
    runs-on: ubuntu-20.04
    name: Run sidecar E2E tests
    steps:
      - name: "Check out code into the Go module directory"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./hack/actions/e2e
        with:
          testsuite_name: sidecar
