name: "End-to-end tests (kuttl)"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  e2e-tests:
    name: End-to-end tests
    runs-on: ubuntu-20.04
    strategy:
      matrix:
       kube-version:
       - "1.19"
       - "1.20"
       - "1.21"
    steps:

      - name: Set up Go
        uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.16

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: "install kuttl"
        run: ./.ci/install-kuttl.sh

      - name: "run tests"
        env:
          KUBE_VERSION: ${{ matrix.kube-version }}
        run: make install kuttl-e2e KUBE_VERSION=$KUBE_VERSION
