name: "End-to-end tests (kuttl)"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  e2e-tests:
    name: End-to-end tests
    runs-on: ubuntu-20.04
    steps:

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: "install kuttl"
        run: ./.ci/install-kuttl.sh

      - name: "run tests"
        run: make install prepare-e2e-kuttl-tests kuttl-e2e
